runtime: nodejs10
# Server isn't working in gCloud because sharing same Project as the actual Pop app.
# Can delete everything below if moved to own Project in gCloud
handlers:
- url: /
  static_files: dist/index.html
  upload: dist/index.html
- url: /about
  static_files: dist/index.html
  upload: dist/index.html
- url: /team
  static_files: dist/index.html
  upload: dist/index.html
- url: /privacy
  static_files: dist/index.html
  upload: dist/index.html
- url: /termsofuse
  static_files: dist/termsOfUse.html
  upload: dist/termsOfUse.html